In [ ]:
# 1. Student Marks Analyzer 
# 2.Matrix Calculator
# 3.Image Processing
# 4.NumPy Based Sudoku Validator

SyntaxError: invalid syntax (98245011.py, line 1)

In [ ]:
import numpy as np

# Generate random marks (50 students, 5 subjects)
marks = np.random.randint(35, 100, size=(50, 5))

print("Marks Matrix:\n", marks)

# Average per student
student_avg = np.mean(marks, axis=1)

# Average per subject
subject_avg = np.mean(marks, axis=0)

print("\nAverage per Student:\n", student_avg)
print("\nAverage per Subject:\n", subject_avg)

# Highest and lowest marks
print("\nHighest Mark:", np.max(marks))
print("Lowest Mark:", np.min(marks))

# Top 5 students
top5 = np.argsort(student_avg)[-5:]
print("\nTop 5 Students Index:", top5)

# Pass count (average > 40)
pass_count = np.sum(student_avg > 40)
print("\nPass Count:", pass_count)


Marks Matrix:
 [[98 96 86 36 41]
 [99 76 97 69 84]
 [51 46 94 81 71]
 [75 80 86 64 54]
 [61 73 88 59 84]
 [79 37 94 82 62]
 [94 78 94 58 78]
 [55 60 44 37 53]
 [97 89 92 78 85]
 [76 50 85 67 76]
 [92 90 43 71 40]
 [52 99 89 75 51]
 [72 92 43 52 85]
 [54 46 97 67 97]
 [39 99 90 47 43]
 [36 85 42 62 90]
 [78 70 40 68 40]
 [57 88 67 89 91]
 [36 98 65 55 82]
 [71 43 75 50 74]
 [41 90 72 72 87]
 [74 44 81 62 38]
 [45 62 58 50 95]
 [45 38 52 69 99]
 [75 46 48 73 71]
 [41 56 59 38 84]
 [96 89 72 76 94]
 [67 61 59 71 53]
 [85 77 40 48 50]
 [56 70 41 76 94]
 [58 62 88 92 78]
 [79 95 47 49 61]
 [85 63 87 69 41]
 [78 78 82 47 92]
 [44 62 41 85 85]
 [50 93 88 86 98]
 [98 61 69 60 63]
 [49 37 65 44 89]
 [72 76 54 53 59]
 [69 63 61 36 58]
 [48 99 57 70 72]
 [87 47 84 56 50]
 [45 35 97 46 53]
 [80 72 62 45 92]
 [62 77 57 82 48]
 [88 95 52 62 39]
 [99 42 77 94 85]
 [64 86 50 83 48]
 [93 36 38 90 86]
 [57 43 77 60 85]]

Average per Student:
 [71.4 85.  68.6 71.8 73.  70.8 80.4 49.8 88.2 70.8 67.2 73.2 

In [2]:
import numpy as np

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

print("\nAddition:\n", A + B)
print("\nSubtraction:\n", A - B)
print("\nMultiplication:\n", np.dot(A, B))
print("\nTranspose of A:\n", A.T)
print("\nDeterminant of A:", np.linalg.det(A))
print("\nInverse of A:\n", np.linalg.inv(A))


Matrix A:
 [[5 8 8]
 [8 2 8]
 [4 7 8]]
Matrix B:
 [[8 6 5]
 [3 9 6]
 [6 3 1]]

Addition:
 [[13 14 13]
 [11 11 14]
 [10 10  9]]

Subtraction:
 [[-3  2  3]
 [ 5 -7  2]
 [-2  4  7]]

Multiplication:
 [[112 126  81]
 [118  90  60]
 [101 111  70]]

Transpose of A:
 [[5 8 4]
 [8 2 7]
 [8 8 8]]

Determinant of A: -72.00000000000006

Inverse of A:
 [[ 0.55555556  0.11111111 -0.66666667]
 [ 0.44444444 -0.11111111 -0.33333333]
 [-0.66666667  0.04166667  0.75      ]]


In [3]:
import numpy as np

# Create random grayscale image
image = np.random.randint(0, 256, (256, 256))

# Increase brightness
bright = np.clip(image + 50, 0, 255)

# Increase contrast
contrast = np.clip(image * 1.5, 0, 255)

# Flip image
flipped = np.flip(image, axis=1)

# Crop image
cropped = image[50:200, 50:200]

print("Original Shape:", image.shape)
print("Cropped Shape:", cropped.shape)


Original Shape: (256, 256)
Cropped Shape: (150, 150)


In [4]:
import numpy as np

def is_valid_group(group):
    """Check if group contains numbers 1-9 exactly once"""
    return np.array_equal(np.sort(group), np.arange(1, 10))

def validate_sudoku(board):
    board = np.array(board)

    # Check shape
    if board.shape != (9, 9):
        return False

    # Check rows
    for row in board:
        if not is_valid_group(row):
            return False

    # Check columns
    for col in board.T:
        if not is_valid_group(col):
            return False

    # Check 3x3 subgrids
    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            subgrid = board[i:i+3, j:j+3].flatten()
            if not is_valid_group(subgrid):
                return False

    return True